# Generated by Django 3.2.10 on 2024-02-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_creator'),
        ('book', '0003_auto_20240217_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default='0c8215af-e98a-4459-ad68-67636fce7b06', on_delete=django.db.models.deletion.CASCADE, to='author.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default='8dd937da-7801-4d84-a99a-be20ca3ccd64', on_delete=django.db.models.deletion.CASCADE, to='book.book'),
            preserve_default=False,
        ),
    ]
